config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  get  '/community',     to: 'posts#index'
  get 'conmmunity/:name', to: 'posts#show'

  get '/home', to: 'pages#home'

  get 'password_resets/new'
  get 'password_resets/edit'

  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts, shallow: true do
  	resources :comments, only: [:create, :destroy]
  end

  default_url_options host: "example.com"
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest:  User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:index, :destroy]

  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user.activated?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:warning] = "Please check your email to activate your account."
      redirect_to "/community"
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User Deleted"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/views/users/index.html.erb
<%= render 'shared/navigation' %>

<%= render 'posts/form' %>

app/views/users/new.html.erb
<% provide(:title, "Sign up to LevelUp!") %>

<div class="text-center">
    <div class="form-signin">
      <%= link_to image_tag("level-up-mush.png", alt: "LevelUp!", class: "signinImg"), root_url %>
      <h3 class="h3 mb-3 font-weight-normal signinH3">SignUp 2 LevelUp!</h3><br>
      <%= form_for(@user, url: signup_path) do |f| %>
        <%= render 'shared/user_error_messages' %>

          <%= f.label :name %>
          <%= f.text_field :name, autofocus: true, class: 'form-control' %><br>

          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %><br>

          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %><br>

          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %><br>

          <%= f.submit "LevelUp!", class: "btn btn-lg btn-primary btn-block" %><br>
          <%= link_to 'Log in', login_url, class: 'btn btn-lg btn-info btn-block'  %><br>

      <% end %>
    </div>
</div>